openapi: 3.0.0
info:
  title: CV4Hire Backend API
  description: API functionality for CV4Hire Backend
  version: 1.0.0
paths:
  /chat:
    post:
      summary: Chat Endpoint
      operationId: chat_endpoint_chat_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /reset:
    get:
      summary: Reset Endpoint
      operationId: reset_endpoint_reset_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /health:
    get:
      summary: Health Check
      operationId: health_check_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components:
  schemas:
    ChatRequest:
      properties:
        user_query:
          type: string
          title: User Query
        session_id:
          type: string
          title: Session Id
          default: default
      type: object
      required:
        - user_query
      title: ChatRequest
    ChatResponse:
      properties:
        sentiment:
          type: string
          title: Sentiment
          default: NEUTRAL
        response:
          type: string
          title: Response
        session_id:
          type: string
          title: Session Id
        agent_used:
          items:
            type: string
          type: array
          title: Agent Used
          default: []
      type: object
      required:
        - response
        - session_id
      title: ChatResponse
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
